CREATE TABLE IF NOT EXISTS PORTFOLIO (
    PORTF_ID    CHAR(10)       NOT NULL PRIMARY KEY,
    OWNER       CHAR(40)       NOT NULL,
    CURRENCY    CHAR(3)        NOT NULL DEFAULT 'USD',
    TOTAL_VALUE DECIMAL(15,2)  NOT NULL DEFAULT 0,
    STATUS      CHAR(1)        NOT NULL DEFAULT 'A',
    LAST_UPD    DATE           NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS TRADE_ORDERS (
    ORDER_ID    CHAR(20)       NOT NULL PRIMARY KEY,
    PORTF_ID    CHAR(10)       NOT NULL,
    ISIN        CHAR(12)       NOT NULL,
    QUANTITY    DECIMAL(15,4)  NOT NULL DEFAULT 0,
    PRICE       DECIMAL(15,4)  NOT NULL DEFAULT 0,
    ORDER_DT    DATE           NOT NULL DEFAULT CURRENT_DATE,
    PROCESS_DT  DATE,
    STATUS      CHAR(4)        NOT NULL DEFAULT 'PEND'
);

CREATE OR REPLACE VIEW ACTIVE_PORTFOLIOS AS
    SELECT * FROM PORTFOLIO
    WHERE STATUS = 'A';
