-- ============================================================
-- CRTTABLES.sql
-- Creates PORTFOLIO and TRADE_ORDERS physical files
-- IBM i Concept: Physical File = DB2 for i base table
-- z/OS Equivalent: VSAM KSDS or DB2 z/OS base table
-- ============================================================

-- Rerunnable cleanup.
-- Drop dependent objects first, then parent objects.
DROP VIEW IF EXISTS CODELIVER1.ACTIVE_PORTFOLIOS;
DROP TABLE IF EXISTS CODELIVER1.TRADE_ORDERS;
DROP TABLE IF EXISTS CODELIVER1.PORTFOLIO;

-- PORTFOLIO: Master portfolio table
CREATE TABLE CODELIVER1.PORTFOLIO (
    PORTF_ID    CHAR(10)      NOT NULL,
    OWNER       CHAR(40)      NOT NULL,
    CURRENCY    CHAR(3)       NOT NULL DEFAULT 'USD',
    TOTAL_VALUE DECIMAL(15,2) NOT NULL DEFAULT 0,
    STATUS      CHAR(1)       NOT NULL DEFAULT 'A',
    LAST_UPD    DATE          NOT NULL DEFAULT CURRENT_DATE
);

ALTER TABLE CODELIVER1.PORTFOLIO
    ADD PRIMARY KEY (PORTF_ID);

-- TRADE_ORDERS: Order staging table
CREATE TABLE CODELIVER1.TRADE_ORDERS (
    ORDER_ID    CHAR(20)      NOT NULL,
    PORTF_ID    CHAR(10)      NOT NULL,
    ISIN        CHAR(12)      NOT NULL,
    QUANTITY    DECIMAL(15,4) NOT NULL DEFAULT 0,
    PRICE       DECIMAL(15,4) NOT NULL DEFAULT 0,
    ORDER_DT    DATE          NOT NULL DEFAULT CURRENT_DATE,
    PROCESS_DT  DATE,
    STATUS      CHAR(4)       NOT NULL DEFAULT 'PEND',
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (PORTF_ID) REFERENCES CODELIVER1.PORTFOLIO(PORTF_ID)
);

-- ACTIVE_PORTFOLIOS: SQL View (Logical File equivalent)
CREATE OR REPLACE VIEW CODELIVER1.ACTIVE_PORTFOLIOS AS
    SELECT * FROM CODELIVER1.PORTFOLIO
    WHERE STATUS = 'A';

-- Seed data
-- Fictional test data only. Names are literary character references,
-- and ISIN-like values are dummy identifiers, not real securities.
INSERT INTO CODELIVER1.PORTFOLIO
    (PORTF_ID, OWNER, CURRENCY, TOTAL_VALUE, STATUS, LAST_UPD)
VALUES
    ('PF001', 'Richard Papen', 'USD', 150000.00, 'A', CURRENT_DATE);

INSERT INTO CODELIVER1.PORTFOLIO
    (PORTF_ID, OWNER, CURRENCY, TOTAL_VALUE, STATUS, LAST_UPD)
VALUES
    ('PF002', 'Henry Winter', 'CHF', 280000.00, 'A', CURRENT_DATE);

INSERT INTO CODELIVER1.PORTFOLIO
    (PORTF_ID, OWNER, CURRENCY, TOTAL_VALUE, STATUS, LAST_UPD)
VALUES
    ('PF003', 'Camilla Macaulay', 'EUR', 95000.00, 'I', CURRENT_DATE);

INSERT INTO CODELIVER1.TRADE_ORDERS
    (ORDER_ID, PORTF_ID, ISIN, QUANTITY, PRICE, ORDER_DT, PROCESS_DT, STATUS)
VALUES
    ('ORD-2026-001', 'PF001', 'TSH000000001', 100, 182.50,
     CURRENT_DATE, NULL, 'PEND');

INSERT INTO CODELIVER1.TRADE_ORDERS
    (ORDER_ID, PORTF_ID, ISIN, QUANTITY, PRICE, ORDER_DT, PROCESS_DT, STATUS)
VALUES
    ('ORD-2026-002', 'PF001', 'TSH000000002', 50, 312.00,
     CURRENT_DATE, NULL, 'PEND');

INSERT INTO CODELIVER1.TRADE_ORDERS
    (ORDER_ID, PORTF_ID, ISIN, QUANTITY, PRICE, ORDER_DT, PROCESS_DT, STATUS)
VALUES
    ('ORD-2026-003', 'PF002', 'TSH000000003', 200, 45.75,
     CURRENT_DATE, NULL, 'PEND');
